Removed DI Logging in favour of static logging as sole solution
mbartelsm/Faultify pull request #15
Opened 2021-05-04 09:50 UTC by mbartelsm

Finally removed the remnants of the old logging system. For the sake of sanity, **do not accept** until after all other branches for this sprint have been merged.

2021-05-06 08:21 UTC, cdadashovkhandan requested changes
Deprecated classes need to be reinstated, otherwise this is good!

2021-05-06 08:21 UTC, cdadashovkhandan commented on Faultify.Cli/ConsoleMessage.cs
>                  + "\n";
Maybe also output data for the excluded mutations?

2021-05-06 08:21 UTC, cdadashovkhandan commented on Faultify.Core/ProjectAnalyzing/ProjectReader.cs
> +                // analyzerManager.SetGlobalProperty("Configuration", "Debug");
Are you sure this should be removed?

2021-05-06 08:21 UTC, cdadashovkhandan commented on Faultify.TestRunner.Collector/CoverageDataCollector.cs
> +    [Obsolete("This class sees no use", true)]
That's not true. This class is fed into `dotnet` to assist data output, therefore it absolutely cannot be deprecated.

It's inserted as a CLI parameter [here](https://github.com/mbartelsm/Faultify/blob/9fb30d00bd84d790cf809342341a953f6beca2be/Faultify.TestRunner/TestRun/TestHostRunners/DotnetTestArgumentBuilder.cs#L28).

2021-05-06 08:21 UTC, cdadashovkhandan commented on Faultify.TestRunner.Collector/TestDataCollector.cs
> +    [Obsolete("This class sees no use", true)]
Cannot be deprecated, see similar comment in `CoverageDataCollector`.

2021-05-07 12:33 UTC, mbartelsm commented on Faultify.Core/ProjectAnalyzing/ProjectReader.cs
> +                // analyzerManager.SetGlobalProperty("Configuration", "Debug");
My bad, that's leftover from other tests and shouldn't be in this PR. Nevertheless, that feature has no actual effects on the program. I added it to enable debug information, but debug information works without it, so there was no need for it in the first place.

2021-05-07 12:33 UTC, mbartelsm commented on Faultify.Cli/ConsoleMessage.cs
>                  + "\n";
Don't think that feature is relevant to the change made here

2021-05-07 12:36 UTC, mbartelsm commented on Faultify.TestRunner.Collector/CoverageDataCollector.cs
> +    [Obsolete("This class sees no use", true)]
In the link you share there is no mention of the class anywhere. The method only takes a string value. Additionally, if the class was used, then an exception would be raised at runtime due to the flag, which doesn't happen when I run the project. Then again, I did not test with dotnet.

2021-05-07 12:41 UTC, mbartelsm commented
I have reverted the problematic changes, as they should not have been in this PR anyway.

2021-05-07 12:47 UTC, cdadashovkhandan commented on Faultify.TestRunner.Collector/CoverageDataCollector.cs
> +    [Obsolete("This class sees no use", true)]
This is a dotnet-specific thing, so naturally you wouldn't get an exception with other test frameworks. Basically, when the CLI argument is built, Faultify specifies itself as a Test Adapter (with the whole `testAdapterPath` thing). That means that `dotnet` uses Faultify itself to assist in testing the target codebase. As a result, the function that I linked, at runtime, links the `CoverageDataCollector` and `TestDataCollector` classes to let `dotnet` know where to dump its data, simply as string values. It doesn't have to link the classes itself since dotnet expects them to be within the test adapter. That's how I understood the whole thing.

See this example `dotnet` command, specifically the two arguments before the last one:

> dotnet test Faultify.Benchmark.NUnit.dll -v s --nologo --blame-hang-timeout 12000ms --test-adapter-path \"C:\\Users\\Vxvl4\\source\\repos\\Faultify\\Faultify.Cli\\bin\\Debug\\netcoreapp3.1\" --collect CoverageDataCollector  --blame-hang-dump-type none

2021-05-08 11:26 UTC, cdadashovkhandan approved these changes
All's good now, good job!

2021-05-10 10:13 UTC, merged