Feat 07 mutation config
mbartelsm/Faultify pull request #16
Opened 2021-05-05 13:31 UTC by H-Monhemius

2021-05-06 07:48 UTC, mbartelsm commented
It's great that you added a document outlining the settings!

2021-05-06 07:54 UTC, mbartelsm requested changes
I would suggest using HashSets instead of lists for storing the exclusions. Particularly because looking up a value in a Hashset is O(1), while it is O(n) for lists. Hashsets also disallow duplicates, which don't make sense in an exclusion list anyway.

2021-05-06 08:12 UTC, cdadashovkhandan approved these changes
Everything seems to be covered and documented properly. Great job!

2021-05-12 13:36 UTC, mbartelsm approved these changes

2021-05-12 13:36 UTC, merged