Documentation PR
mbartelsm/Faultify pull request #30
Opened 2021-05-24 14:31 UTC by JFaber151

added documentation and some refactoring. Covering everything but the testProcess package

2021-05-25 11:11 UTC, cdadashovkhandan requested changes
Tiny nitpicks here and there, but otherwise good job! Please tend to them, as this is important documentation.

2021-05-25 11:11 UTC, cdadashovkhandan commented on Faultify.Analyze/RandomValueGenerator.cs
> -                if (type == typeof(bool))
Why was this moved to a new method?

2021-05-25 11:11 UTC, cdadashovkhandan commented on Faultify.Core/ProjectAnalyzing/ProjectReader.cs
> +        ///     Analye the project and return the results
Typo

2021-05-25 11:11 UTC, cdadashovkhandan commented on Faultify.Cli/Program.cs
> +        ///     Perform the setup to create the faultify program
Might wanna capitalize `faultify` for good measure

2021-05-25 11:11 UTC, cdadashovkhandan commented on Faultify.Analyze/RandomValueGenerator.cs
> -                if (type == typeof(bool))
the new method seems to be pretty much the exact same size, so I think moving this to a new method just makes it confusing

2021-05-25 11:11 UTC, cdadashovkhandan commented on Faultify.Core/ProjectAnalyzing/ProjectReader.cs
>          public Task<IProjectInfo> ReadProjectAsync(string path, IProgress<string> progress)
If the parent interface doesn't have this commented, you might wanna add a small comment

2021-05-25 12:42 UTC, JFaber151 commented on Faultify.Analyze/RandomValueGenerator.cs
> -                if (type == typeof(bool))
Personally, I like the readability of 'oh, it just makes a new reference for that type. And as for how that is done, you've got the other method. But I can change it back

2021-05-25 16:06 UTC, cdadashovkhandan requested changes
I think it's best to follow a more consistent convention in terms of commenting, such as

`/// Attempt to read X and insert it into Y`

instead of 

`/// We try to read X, if it exists, we insert it into Y`

Other than that, good job! The direct code refactors are pretty smart and neat.

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/CoverageRegistry.cs
> +        ///     Try to write to the mutation coverage fail if the process exits
I don't think "fail if the process exits" is necessary here

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     We get the method definition, if it's empty, we create a new method definition instead
Don't think a "we" is necessary here in either of the sentences.

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     We get the method definition, if it's empty, we create a new method definition instead
Perhaps you could rephrase it as "Get new or existing method definition"

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/TestCoverageInjector.cs
> +        private MethodDefinition GetOrMake(MethodAttributes moduleInitAttributes, ModuleDefinition toInjectModule, TypeReference returnType)
maybe just call it "GetCctor" ?

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     We check if the call is already done
No need for "we"

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     We check if the call is already done
In general, when writing these comments, mostly focus on the scenario of someone reading this description as they hover over a method name. Therefore, they should just be a quick concise definition that serves as an annotation for the thing they're describing.

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     We add the method, and add any ret instruction if necessary
See previous comment

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     Get the opcode instructions, and insert them. Including the assmebly name
Typo at "assmebly"

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.Injection/TestCoverageInjector.cs
> +        private void InsertInstructions(MethodDefinition method, MethodReference registerMethodReference)
Are you sure this comment matches what it's describing?

2021-05-25 16:06 UTC, cdadashovkhandan commented on Faultify.TestRunner/MutationTestProject.cs
> +        ///     Foreach project reference load it in memory as an 'assembly mutator'.
might want to change `'assembly mutator'`  to `AssemblyMutator`

2021-05-26 08:31 UTC, mbartelsm commented on Faultify.TestRunner/MutationTestProject.cs
> +        ///     Foreach project reference load it in memory as an 'assembly mutator'.
```suggestion
        ///     Foreach project reference load it in memory as an <see cref="AssemblyMutator"/>.
```

2021-05-26 08:31 UTC, mbartelsm commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     Get the opcode instructions, and insert them. Including the assmebly name
```suggestion
        ///     Get the opcode instructions, and insert them. Including the assembly name
```

2021-05-26 08:31 UTC, mbartelsm commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     We add the method, and add any ret instruction if necessary
```suggestion
        ///     Add the method, and add any ret instruction if necessary
```

2021-05-26 08:32 UTC, mbartelsm commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     We check if the call is already done
```suggestion
        ///     Check if the call is already done
```

2021-05-26 08:32 UTC, mbartelsm commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     We get the method definition, if it's empty, we create a new method definition instead
```suggestion
        ///     Get the method definition. If it's empty, create a new method definition instead
```

2021-05-26 08:33 UTC, mbartelsm commented on Faultify.Injection/CoverageRegistry.cs
> +        ///     Try to write to the mutation coverage fail if the process exits
```suggestion
        ///     Try to write to the mutation coverage fail
```

2021-05-26 08:36 UTC, mbartelsm commented on Faultify.Injection/TestCoverageInjector.cs
> +        ///     Get the opcode instructions, and insert them. Including the assmebly name
```suggestion
        ///     Insert a callback to the register function
```

2021-05-26 08:40 UTC, mbartelsm commented on Faultify.Injection/TestCoverageInjector.cs
> +        private MethodDefinition GetOrMake(MethodAttributes moduleInitAttributes, ModuleDefinition toInjectModule, TypeReference returnType)
Cannot change this from the PR, it's up to @JFaber151 to do it locally

2021-05-26 08:54 UTC, merged